### ISSUE TITLE
Cannot get plugin to work in gedit 3.14 (Debian Testing)

### ISSUE THREAD

**Issue by speendo** [bittner/gedit-reST-plugin#6]
I cannot get the plugin running on Debian x64 (Testing) with gedit 3.14

Here's the error message:
http://imgur.com/htAc538

Please contact me, if I can provide any additional information.

**Comment by bittner** [comment]
Can you please start `gedit` from a terminal, reproduce the situation of the screenshot, and paste the error output (in the terminal) here?
Most probably, some paths are different on Debian as opposed to Ubuntu, or you're using Python 2.7 instead of Python 3.

**Comment by speendo** [comment]
Thanks for the reply!

I'd love to, but when I start gedit in a terminal, I don't "see it" in the terminal anymore.

I type "$ gedit", a gedit window opens but the terminal shows me a new prompt.

I thought, maybe gedit is backgrounded, but "$ fg" wouldn't get it to the foreground as well.

I don't know how to get debug information. Do you have an idea?

**Comment by bittner** [comment]
I'm running `gedit` version 3.10.4 in a GNOME Terminal version 3.6.2 on an (Ed)ubuntu 14.04 Trusty box, and it opens in foreground spitting out (debug) output on the console. -- Try one of the following:

* Try `gnome-text-editor`
* Check whether `gedit` points to a binary, or it's an alias, or whatever (`alias gedit`, `which gedit`, `ls -lAF --color=auto $(which gedit)`, `ps aux | grep [g]edit`, ...)
* Install and use [reptyr](http://stackoverflow.com/questions/9047581/capture-stdin-stderr-stdout-of-a-process-after-its-been-started-using-comm), e.g.
```
sudo apt-get install reptyr
PID=`ps -A | grep [g]edit | sed -E -e 's/\s*//' -e '\s+.*//'`
reptyr -s $PID
```
As soon as you can see text output of `gedit` on the terminal console go to Edit -> Preferences -> Plugins in gedit, and deactivate and re-activate the reST plugin.

**Comment by speendo** [comment]
Hey!

`gnome-text-editor` worked. Cool!

Here's the output:

    $ gnome-text-editor
    ImportError: No module named 'reST'

    (gnome-text-editor:2287): libpeas-WARNING **: Error loading plugin 'reST'

By the way - Python 3 is at least installed - but Python 2.7 is the standard.

**Comment by bittner** [comment]
Good, so the plugin (i.e. the Python module `reST`) is not found in the gedit plugins folder.
Can you please follow the [installation process](https://github.com/bittner/gedit-reST-plugin#installation) step by step, and let me know whether both the `reST` folder and the `reST.plugin` file are in either your local or the system's global plugin folder for gedit?

**Comment by speendo** [comment]
Thank you for your support!

Previously I linked the plugin and the `reST`-folder to the `/plugins`-folder. Obviously, that didn't work. Now I copied them there, which solved the issue. I can now activate the plugin. However, the plugin doesn't work yet. I get

    $ gnome-text-editor
    Traceback (most recent call last):
      File "/home/<username>/.local/share/gedit/plugins/reST/__init__.py", line 116, in do_activate
        bottom.add_item(scrolled_window, "rest-preview", "reStructuredText Preview", image)
    AttributeError: 'Stack' object has no attribute 'add_item'

Maybe it's my fault and not the fault of the plugin (again).

**Comment by bittner** [comment]
Looks like an API change that other gedit plugins experience as well (e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=746430 and [related changes](https://github.com/toobaz/gedit-source-code-browser/commit/886840b7b3c07d46329d7f63ce197064b114b8c1)). I'll try to figure out what to do (in order to keep the plugin working also for gedit < v3.12). Would be nice if you could play the guinea pig and test the resulting code. Please drop me an email (see my profile).

**Comment by speendo** [comment]
of course!

**Comment by bittner** [comment]
I have overhauled the code base, and the basics of the plugin are now working in Gedit 3.14. The working code is currently in the [gedit-3.14 branch](/bittner/gedit-reST-plugin/tree/gedit-3.14). Please clone the source code as follows and follow the [README](/bittner/gedit-reST-plugin/blob/gedit-3.14/README.rst):
``` bash
$ git clone -b gedit-3.14 git@github.com:bittner/gedit-reST-plugin.git
```
Thanks @speendo for testing even though you're already using another editor!

Rendering is automatic at the moment (i.e. each change triggers a re-generation of the HTML to be displayed). I couldn't manage to integrate the menu actions yet (Ctrl+R to render, etc.). I would clean up the source files afterwards and "release" version 3.14 by tagging a commit. (PRs welcome!)
Until then please use the `gedit-3.14` branch!
